# Site settings
title: Junior Conference on Data Science and Engineering
title_short:  Paris-Saclay &#35JDSE2018   #JDSE Paris-Saclay 2018
email:
url: https://jdse-paris.github.io/jDSEParis18/
description: "Paris-Saclay Junior Conference on Data Science and Engineering"
meta_author: Jacob Montiel maj 2017 Flora Jay maj 2018 Olivier Fercoq
skills: "Paris-Saclay, 12th-13th September 2018"

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: #Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #  url: # http://twitter.com/jekyllrb
  # 2017 twitter page:
  - title: twitter
    url: https://www.twitter.com/JDSEParisSaclay
    share: <a href="https://twitter.com/hashtag/JDSE2018?src=hash"> &#35JDSE2018 </a>
    hashtag: "#JDSE2018"
    
  
# Postal address (add as many lines as necessary)
address:
  - line: <a href="https://www.universite-paris-saclay.fr/fr">Université Paris-Saclay</a>
  - line: Paris, France

# Credits content

credits: 
  <a href="mailto:olivier.fercoq@telecom-paristech.fr" target="_top">olivier.fercoq@telecom-paristech.fr</a>
  <a href="mailto:fatiha.sais@lri.fr; " target="_top">fatiha.sais@lri.fr</a>

# Build settings
permalink: pretty

# Updates for compatibility with the new github environment:
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge
future: true

gems:
  - jekyll-paginate
  - jekyll-gist





